### ISSUE TITLE
Spacer widget cannot take a background color

### ISSUE THREAD

**Issue by Cur10** [qtile/qtile#1300]
In the documentation it says the spacer widget can use a background however when it is added in the bar, it errors out.

**Comment by ramnes** [comment]
It has been fixed by @krive001 pull request. Thank you for reporting this @Cur10!

**Comment by SpyrosRoum** [comment]
Hello, I still get `TypeError: __init__() got an unexpected keyword argument 'background'` if I try to put background in a spacer widget

**Comment by ramnes** [comment]
Hey @SpyrosRoum, thanks for raising this. Did you install Qtile from sources? This patch hasn't been released yet.

**Comment by SpyrosRoum** [comment]
Oh sorry, I installed from pacman and I thought it was out
