### ISSUE TITLE
Qtile doesn't start after Archlinux update

### ISSUE THREAD

**Issue by zordsdavini** [qtile/qtile#1326]
I get  (re)starting error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/ipc.py", line 144, in send
    _, client_proto = self.loop.run_until_complete(client_coroutine)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 232, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 464, in sock_connect
    return await fut
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 469, in _sock_connect
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/qshell", line 11, in <module>
    load_entry_point('qtile==0.13.0', 'console_scripts', 'qshell')()
  File "/usr/lib/python3.7/site-packages/libqtile/scripts/qshell.py", line 68, in main
    qsh.loop()
  File "/usr/lib/python3.7/site-packages/libqtile/sh.py", line 326, in loop
    val = self.process_command(line)
  File "/usr/lib/python3.7/site-packages/libqtile/sh.py", line 308, in process_command
    val = self._call(cmd, args)
  File "/usr/lib/python3.7/site-packages/libqtile/sh.py", line 266, in _call
    cmds = self._commands
  File "/usr/lib/python3.7/site-packages/libqtile/sh.py", line 131, in _commands
    return self.current.commands()
  File "/usr/lib/python3.7/site-packages/libqtile/command.py", line 114, in __call__
    return self.call(self.selectors, self.name, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/libqtile/command.py", line 251, in call
    state, val = self.client.call((selectors, name, args, kwargs))
  File "/usr/lib/python3.7/site-packages/libqtile/ipc.py", line 158, in call
    return self.send(data)
  File "/usr/lib/python3.7/site-packages/libqtile/ipc.py", line 146, in send
    raise IPCError("Could not open %s" % self.fname)
libqtile.ipc.IPCError: Could not open /home/arnas/.cache/qtile/qtilesocket.:1.0
exit 1
```

I did qtile-python3-git version update + all archlinux
```
[2019-05-23 06:25] [ALPM] upgraded linux-firmware (20190424.4b6cf2b-1 -> 20190514.711d329-1)
[2019-05-23 06:25] [ALPM] upgraded e2fsprogs (1.45.0-1 -> 1.45.1-1)
[2019-05-23 06:25] [ALPM] upgraded krb5 (1.16.1-1 -> 1.16.2-1)
[2019-05-23 06:25] [ALPM] upgraded dbus (1.12.12-1 -> 1.12.14-1)
[2019-05-23 06:25] [ALPM] upgraded shadow (4.6-2 -> 4.6-3)
[2019-05-23 06:25] [ALPM] upgraded ca-certificates-mozilla (3.43-1 -> 3.44-1)
[2019-05-23 06:25] [ALPM] upgraded glib2 (2.60.2-1 -> 2.60.3-1)
[2019-05-23 06:25] [ALPM] upgraded libssh2 (1.8.1-1 -> 1.8.2-1)
[2019-05-23 06:25] [ALPM] upgraded file (5.36-1 -> 5.37-1)
[2019-05-23 06:25] [ALPM] upgraded glib2-docs (2.60.2-1 -> 2.60.3-1)
[2019-05-23 06:25] [ALPM] upgraded linux-lts (4.19.42-1 -> 4.19.44-1)
[2019-05-23 06:25] [ALPM] upgraded linux (5.0.13.arch1-1 -> 5.1.4.arch1-1)
[2019-05-23 06:25] [ALPM] upgraded nss (3.43-1 -> 3.44-1)
[2019-05-23 06:25] [ALPM] upgraded btrfs-progs (4.20.2-1 -> 5.1-1)
[2019-05-23 06:25] [ALPM] upgraded libxnvctrl (418.74-1 -> 430.14-1)
[2019-05-23 06:25] [ALPM] upgraded nvidia-utils (418.74-1 -> 430.14-1)
[2019-05-23 06:25] [ALPM-SCRIPTLET] If you run into trouble with CUDA not being available, run nvidia-modprobe first.
[2019-05-23 06:25] [ALPM] upgraded mesa (19.0.3-1 -> 19.0.4-1)
[2019-05-23 06:25] [ALPM] upgraded librsvg (2:2.44.13-1 -> 2:2.44.14-1)
[2019-05-23 06:25] [ALPM] installed js60 (60.7.0-1)
[2019-05-23 06:25] [ALPM] upgraded polkit (0.115+24+g5230646-1 -> 0.116-1)
[2019-05-23 06:25] [ALPM] upgraded alsa-lib (1.1.8-1 -> 1.1.9-1)
[2019-05-23 06:25] [ALPM] upgraded libsoup (2.66.1-1 -> 2.66.2-1)
[2019-05-23 06:25] [ALPM] upgraded webkit2gtk (2.24.1-1 -> 2.24.2-1)
[2019-05-23 06:25] [ALPM] upgraded python-requests (2.21.0-1 -> 2.22.0-1)
[2019-05-23 06:25] [ALPM] upgraded postgresql-libs (11.2-3 -> 11.3-1)
[2019-05-23 06:25] [ALPM] upgraded python-cairo (1.18.0-1 -> 1.18.1-1)
[2019-05-23 06:25] [ALPM] upgraded mariadb-libs (10.3.14-1 -> 10.3.15-1)
[2019-05-23 06:25] [ALPM] upgraded tslib (1.19-1 -> 1.20-1)
[2019-05-23 06:25] [ALPM] upgraded qt5-declarative (5.12.3-1 -> 5.12.3-2)
[2019-05-23 06:25] [ALPM] upgraded qt5-webkit (5.212.0alpha2-28 -> 5.212.0alpha2+156+g95401fe3908-1)
[2019-05-23 06:25] [ALPM] upgraded nvidia-settings (418.74-1 -> 430.14-1)
[2019-05-23 06:25] [ALPM] upgraded alsa-utils (1.1.8-1 -> 1.1.9-1)
[2019-05-23 06:25] [ALPM] upgraded ctags (1:r20181015+g45968eff-1 -> 1:r20190522+g3fdf28bc-1)
[2019-05-23 06:25] [ALPM] upgraded nvidia (418.74-1 -> 430.14-4)
[2019-05-23 06:26] [ALPM] upgraded firefox (66.0.5-1 -> 67.0-1)
[2019-05-23 06:26] [ALPM] upgraded exiv2 (0.26-2 -> 0.27.1-1)
[2019-05-23 06:26] [ALPM] upgraded python2-cairo (1.18.0-1 -> 1.18.1-1)
[2019-05-23 06:26] [ALPM] upgraded imagemagick (7.0.8.45-1 -> 7.0.8.46-1)
[2019-05-23 06:26] [ALPM] upgraded vlc (3.0.6-11 -> 3.0.6-12)
[2019-05-23 06:26] [ALPM] upgraded geoclue (2.5.2-3 -> 2.5.3-1)
[2019-05-23 06:26] [ALPM] upgraded perl-mailtools (2.20-2 -> 2.21-1)
[2019-05-23 06:26] [ALPM] upgraded nvidia-lts (1:418.74-2 -> 1:430.14-1)
[2019-05-23 06:26] [ALPM] upgraded qpdf (8.4.1-1 -> 8.4.2-1)
[2019-05-23 06:26] [ALPM] upgraded ethtool (1:5.0-1 -> 1:5.1-1)
[2019-05-23 06:26] [ALPM] upgraded libmagick6 (6.9.10.41-1 -> 6.9.10.46-1)
[2019-05-23 06:26] [ALPM] upgraded libuv (1.28.0-1 -> 1.29.1-1)
[2019-05-23 06:26] [ALPM] upgraded intel-ucode (20190312-1 -> 20190514.a-1)
[2019-05-23 06:26] [ALPM] upgraded gtk-doc (1.30+1+g44c5972-1 -> 1.30+1+g44c5972-2)
[2019-05-23 06:26] [ALPM] upgraded alsa-plugins (1.1.8-1 -> 1.1.9-2)
[2019-05-23 06:26] [ALPM] upgraded perl-net-http (6.18-2 -> 6.19-1)
[2019-05-23 06:26] [ALPM] upgraded metis (5.1.0.p5-1 -> 5.1.0.p6-1)
[2019-05-23 06:26] [ALPM] upgraded libreoffice-fresh (6.2.3-2 -> 6.2.4-1)
[2019-05-23 06:26] [ALPM] upgraded bind-tools (9.14.1-1 -> 9.14.2-1)
[2019-05-23 06:26] [ALPM] upgraded darktable (2:2.6.2-1 -> 2:2.6.2-2)
[2019-05-23 06:26] [ALPM] upgraded python-docker (3.7.2-1 -> 4.0.1-1)
[2019-05-23 06:26] [ALPM] upgraded python-markdown (3.0.1-2 -> 3.1-1)
[2019-05-23 06:26] [ALPM] upgraded dbeaver (6.0.3-1 -> 6.0.4-1)
[2019-05-23 06:26] [ALPM] upgraded bbswitch (0.8-217 -> 0.8-223)
[2019-05-23 06:26] [ALPM] upgraded android-file-transfer (3.7-2 -> 3.8-1)
[2019-05-23 06:26] [ALPM] upgraded libgexiv2 (0.12.0-1 -> 0.12.0-2)
[2019-05-23 06:26] [ALPM] upgraded tmux (2.9_a-1 -> 2.9_a-2)
[2019-05-23 06:26] [ALPM] upgraded go (2:1.12.4-1 -> 2:1.12.5-1)
[2019-05-23 06:26] [ALPM] upgraded python-distlib (0.2.8-1 -> 0.2.9-1)
```

**Comment by zordsdavini** [comment]
what I tried:
- downgrade python-cairo
- reinstalling python-cairocffi

other WM works (dwm)

**Comment by flacjacket** [comment]
Where are you seeing this? What's interesting is that this is coming out of the IPC client, which I wouldn't expect to see coming from the qtile server.

**Comment by zordsdavini** [comment]
This is from qshell restart

2019 m. geg. 24 d., pn 04:32, Sean Vig <notifications@github.com> rašė:

**Comment by zordsdavini** [comment]
maybe error comes from ipc as (maybe) qtile server is dead

other more errors what I found in log:

```
2019-05-23 22:38:08,756 ERROR libqtile manager.py:<lambda>():L273 Got an exception in poll loop
Traceback (most recent call last):
  File "/home/arnas/Skleps/qtile/libqtile/core/manager.py", line 723, in _xpoll
    e = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 568, in wrapper
    self.invalid()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 558, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/arnas/Skleps/qtile/libqtile/core/manager.py", line 754, in _xpoll
    self.stop()
  File "/home/arnas/Skleps/qtile/libqtile/core/manager.py", line 804, in stop
    self.graceful_shutdown()
  File "/home/arnas/Skleps/qtile/libqtile/core/manager.py", line 774, in graceful_shutdown
    pids = list(filter(lambda x: x is not None, pids))
  File "/home/arnas/Skleps/qtile/libqtile/core/manager.py", line 772, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/home/arnas/Skleps/qtile/libqtile/core/xcbq.py", line 612, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/home/arnas/Skleps/qtile/libqtile/core/xcbq.py", line 713, in get_property
    0, (2 ** 32) - 1
  File "/usr/lib/python3.7/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 390, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 568, in wrapper
    self.invalid()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 558, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
```

**Comment by zordsdavini** [comment]
I tried various starts and now I see what I can't get real logs. How can I add more logging?

**Comment by ramnes** [comment]
@zordsdavini By doing nasty things with Qtile, I've had the exact same error than on your latest traceback. My `.Xauthority` file ended up owned by another user (root, here). I fixed it with `sudo rm -f .Xauthority`. Did you check the file permissions all around?

**Comment by zordsdavini** [comment]
Tried to remove `.Xauthority` - didn't helped. Tried xephyr script - it runs. Tried default config - qtile starts but keybindings doesn't work. Debug gives ex. `2019-06-04 00:32:24,850 INFO libqtile manager.py:handle_KeyPress():L947 Ignoring unknown keysym: 65513`

**Comment by zordsdavini** [comment]
With the last version of dev I got it working. Though if I add graph widgets - I crash. But this is what I can test. I've added psutils but still failing.
