### ISSUE TITLE
Turning screen off and on again creates some issues

### ISSUE THREAD

**Issue by tcld** [qtile/qtile#2313]
# Issue description

I have observed an **issue with my systray and the assigment of groups to specific screens after turning off all my screens and then turning one or more back on**. I don't know whether this issue only shows up when using multiple screens.

*A bit more detail:*
After Qtile starts up, I assign a specific group to each screen through a function in my config. This works fine. After turning screens off and on, however, I end up with the standard groups being selected - i.e. group 1 for screen 1, group 2 for screen 2, etc.
I have set up a fake screen, so I am using `qtile.config.fake_screens` for my setup, not `qtile.config.screens`. I have not tested the other variable so far.

On top of that, the layout of my systray icons is broken after I turn on the screens again. I have observed this before when testing #1899 after restarting Qtile. @m-col : Do you think the issues could be related to that PR? (I have nothing tied to the `screen_change`-hook.)

# Qtile version

Most recent master.

# Stack traces

There actually is a bit of a stacktrace that might be related to this:

```log
2021-03-21 08:16:29,679 ERROR libqtile core.py:_xpoll():L313 Got an exception in poll loop
Traceback (most recent call last):
  File "/home/tcl/Software/qtile/libqtile/backend/x11/core.py", line 281, in _xpoll
    ret = target(event)
  File "/home/tcl/Software/qtile/libqtile/widget/systray.py", line 88, in handle_DestroyNotify
    del(self.systray.icons[wid])
KeyError: 23068737
2021-03-21 08:16:30,406 ERROR libqtile core.py:_xpoll():L313 Got an exception in poll loop
Traceback (most recent call last):
  File "/home/tcl/Software/qtile/libqtile/backend/x11/core.py", line 281, in _xpoll
    ret = target(event)
  File "/home/tcl/Software/qtile/libqtile/widget/systray.py", line 88, in handle_DestroyNotify
    del(self.systray.icons[wid])
KeyError: 23068745
```

# Configuration

```python
@hook.subscribe.screen_change
def restart_on_add_screen(ev):
    # reload_screen()
    # libqtile.qtile.cmd_restart()
    pass

fake_screens = init_fakescreens()
```

**Comment by tcld** [comment]
This is what the systray looks like (ignore the colors):
![image](https://user-images.githubusercontent.com/12257447/111897624-4ae4e200-8a21-11eb-8ecc-43fdbed05d30.png)

This is what it should normally look like:
![screenshot_2021-03-21_08-39-19_136x29](https://user-images.githubusercontent.com/12257447/111897640-7c5dad80-8a21-11eb-8c67-b33f16c80801.png)

The issues also occur when I only turn off/on one of my screens.

**Comment by m-col** [comment]
Is reproduction of the issue completely reliable? If it is can you check before and after #1899 to confirm that it introduced the problem?

**Comment by m-col** [comment]
Also when you turn on and off screens is this changing randr configuration (i.e. via autorandr or similar)?

**Comment by tcld** [comment]
Reproduction is reliable. I'll go back and compare the situation.

I have no configuration for autorandr prepared, but since it is installed it might be doing something without me knowing. I'll try to uninstall it, too.

**Comment by tcld** [comment]
I checked the commits, and it is definitely https://github.com/qtile/qtile/commit/9e6af506cd714fc993c5b7f534c689b80cc21793 that introduces the issues.

Everything also happens after uninstalling `autorandr`.

**Comment by kiniou** [comment]
I'm not on master but on v0.17.0 and I also stumble on those systray KeyError exceptions after resizing the Qtile screen when I change resolution with xrandr and quit the app in systray.
 
I'm doing the following in `screen_change` event subscribe:
```
@hook.subscribe.screen_change
def restart_on_randr(event):
    for screen in qtile.screens:
        screen.resize(w=event.width, h=event.height)
```
I'm doing this mostly because when I change resolution, Qtile does not follow and does not update my screen accordingly (see here the bottom bar in the middle of the screen)
![image](https://user-images.githubusercontent.com/121836/112754594-0cc95e80-8fdd-11eb-941e-384277bcd851.png)

I'm also seeing the painting of systray icons in random places like here with the slack icon:
![image](https://user-images.githubusercontent.com/121836/112754670-6f225f00-8fdd-11eb-83b0-b32b9f19c348.png)

And the KeyError exception occurs when I quit the slack application:
```
Traceback (most recent call last):
  File "qtile/libqtile/backend/x11/core.py", line 273, in _xpoll
    ret = target(event)
  File "qtile/libqtile/widget/systray.py", line 88, in handle_DestroyNotify
    del(self.systray.icons[wid])
KeyError: 54525979
```
I think the issue is global to every systray icons since I've also the issue with Steam systray icon.

**Comment by m-col** [comment]
Do you have `reconfigure_screens` set to True in your config?

**Comment by m-col** [comment]
Hey guys, could you confirm that https://github.com/qtile/qtile/pull/2372 fixes the systray issue?

**Comment by tcld** [comment]
I did just a quick test, and the systray-issue appears to be fixed with that PR.

(The group-assignments are still wrong after turning the screen off and on.)

**Comment by kiniou** [comment]
I also tested the PR (after switching to master in order to apply the patch since there are a lot of needed changes since v0.17) and I also confirm the issue with systray painting is gone. Thanks 👍

> Do you have `reconfigure_screens` set to True in your config?
@m-col : I don't have this variable in my configuration and it does not seems to exist in [v0.17](http://docs.qtile.org/en/v0.17.0/manual/config/index.html)
Now that I'm on master and this variable is on by default, i've removed my resize workaround and screen is correctly resized after resolution changes with xrandr.
I think i'll stick with master a little bit until v0.18 is released 😁.

**Comment by m-col** [comment]
@tcld Is the group issue fixed by https://github.com/qtile/qtile/pull/2399?

**Comment by tcld** [comment]
I'll give it a try later today.

**Comment by tcld** [comment]
#2399 doesn't seem to fix the group issue for me; although I am using fake_screens instead of screens - maybe that has something to do with it?

**Comment by m-col** [comment]
@tcld how about now?

**Comment by tcld** [comment]
Yes, now it works. Thank you! :)
