### ISSUE TITLE
Fixed aspect ratio windows get too big if full screened

### ISSUE THREAD

**Issue by TIAcode** [qtile/qtile#2512]
# Issue description

Windows with fixed aspect ratio (like mpv) go over the screen area when full screened. I have 1920x1080 resolution screen, and if I full screen a mpv playing video with resolution 1920x1200, I get 1920x1200 screen instead of full screen, losing a part of the video. My guess is qtile forces the aspect ratio after resizing. Other window manager that also forces fixed aspect ratios for floating windows did not have that issue.

# Qtile version
Issue was not present int 0.17.0. It is present in current git version, hash 6799b6ae5ea09454e5d4ebeb82c0f0909af39439

# Stack traces

No meaningful logs from qtile. mpv when fullscreening:

```
[cplayer] Set property: fullscreen -> 1
[vo/gpu] Resize: 568x336
[vo/gpu] Window size: 568x336 (Borders: l=0 t=0 r=0 b=0)
[vo/gpu] Video source: 1920x1200 (1:1)
[vo/gpu] Video display: (0, 0) 1920x1200 -> (15, 0) 537x336
[vo/gpu] Video scale: 0.279687/0.280000
[vo/gpu] OSD borders: l=15 t=0 r=16 b=0
[vo/gpu] Video borders: l=15 t=0 r=16 b=0
[vo/gpu] Reported display depth: 8
[statusline] (Paused) AV: 00:00:01 / 00:10:41 (0%) A-V:  0.000
[cplayer] Set property: shared-script-properties -> 1
[vo/gpu] Resize: 1920x1200
[vo/gpu] Window size: 1920x1200 (Borders: l=0 t=0 r=0 b=0)
[vo/gpu] Video source: 1920x1200 (1:1)
[vo/gpu] Video display: (0, 0) 1920x1200 -> (0, 0) 1920x1200
[vo/gpu] Video scale: 1.000000/1.000000
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0
[vo/gpu] Reported display depth: 8
[cplayer] Set property: shared-script-properties -> 1
[statusline] (Paused) AV: 00:00:01 / 00:10:41 (0%) A-V:  0.000
[vo/gpu] Resize: 1920x1200
[vo/gpu] Window size: 1920x1200 (Borders: l=0 t=0 r=0 b=0)
[vo/gpu] Video source: 1920x1200 (1:1)
[vo/gpu] Video display: (0, 0) 1920x1200 -> (0, 0) 1920x1200
[vo/gpu] Video scale: 1.000000/1.000000
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0

```
# Configuration

Issue is present in default configuration.

**Comment by ramnes** [comment]
I can confirm, I've seen this a few weeks after we merge the PAspect PR. We probably need to make an exception for fullscreen windows, or watch another flag. What other WM did you try that respect aspect but don't have this problem?

**Comment by TIAcode** [comment]
> What other WM did you try that respect aspect but don't have this problem?

That was i3wm.

**Comment by m-col** [comment]
I've addressed this in #2564 which to me seems to work well. Please could someone test it out and confirm? Just to get a second test :)

**Comment by ramnes** [comment]
Just tried the fix and it seems quite brittle to me: if I "cmd_toggle_fullscreen" a floating window, it will still get over screen boundaries. It only works if I 1/ unfloat the window and 2/ toggle fullscreen.
