### ISSUE TITLE
unity game engine window problem

### ISSUE THREAD

**Issue by ArchKubi** [qtile/qtile#2996]
### The bug:

arch linux 0.18.1 version
my problem unity game engine screen problem
![2021-11-08-222741_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/140828142-05175551-a1cd-4b9e-8a20-bfff6aac4e8e.png)

### 

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Please could you post:

- your config
- any log output from when the bug happens

**Comment by ArchKubi** [comment]
[qtile.log](https://github.com/qtile/qtile/files/7512080/qtile.log)


Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
Checking for update
Update for version 2.4.5 is not available (latest version: 2.4.5, downgrade is disallowed).
Checking for update
Found version 3.0.0-beta.6 (url: UnityHubBeta.AppImage)
Checking for update
Update for version 2.4.5 is not available (latest version: 2.4.5, downgrade is disallowed).
Checking for update
Found version 3.0.0-beta.6 (url: UnityHubBeta.AppImage)

**Comment by ACosmicWolf** [comment]
i had the same issue i solved it by adding float_rules to unity.

**Comment by elParaguayo** [comment]
@ArchKubi does the above fix resolve your issue? If so, can we close this?

**Comment by m-col** [comment]
I tried to install Unity to test this out myself but (in addition to being insanely huge) it seemed like I needed a license? @elParaguayo by any chance do you have it installed already?

It would be nice to confirm we don't have a bug somewhere.

**Comment by elParaguayo** [comment]
Nope. Don't have it installed either. Can get a free licence but it's a pain and I'd rather have the OP confirm the issue is solved if possible.

**Comment by geekosaur** [comment]
For what it's worth, this was reported in xmonad as well and it turned out that it behaved correctly if a compositor was running. We treated it as a Unity bug.

(You can get an eval / personal use license for Unity from their website.)

**Comment by m-col** [comment]
@geekosaur Great, thank you very much. @ArchKubi does the issue persist if you use a compositor?

**Comment by ArchKubi** [comment]
ı don't know ı'am not test

**Comment by m-col** [comment]
Could you test, e.g. with `picom`?

**Comment by ArchKubi** [comment]
ı download unity and ı test seems okay
![2022-02-02-074549_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/152094616-e7e42f03-529c-4bb1-ba21-a67aacf0bba2.png)
