### ISSUE TITLE
First time installation of `qtile-git` from the AUR fails

### ISSUE THREAD

**Issue by thingsiplay** [qtile/qtile#3393]
```
FAILED test_widget_init_config[1-x11-ImapWidget-kwargs28]
FAILED test_widget_init_config[1-wayland-ImapWidget-kwargs28] 

2 failed, 1192 passed, 41 skipped in 942.51s (0:15:42)
```
I am on Manjaro and use Qtile on X11 (Nvidia thanks). Finally my Manjaro distribution updated python-wlroots, so I was able to build Qtile from Git. But it does not complete build process, because 2 tests fail. I include the messages at the end of the output as a file, after the tests. Also here basic information about my system with a fetch program:

```
OS: Manjaro Linux [x86_64]
Kernel: 5.16.11-2-MANJARO
Uptime: 37 mins
Packages: 1877 (pacman)[stable], 1 (flatpak)
Shell: zsh 5.8.1
Resolution: 2560x1440 @ 144Hz
DE: KDE Plasma 5.24.2

WM: Qtile 0.20.0
Theme: breeze (GruvboxColorsBreathLight) [Plasma], Klaus [GTK2/3/4]
Icons: Gruvboxbreeze [Plasma], Gruvbox [GTK2/3/4]
Font: Noto Sans (12pt) [Plasma], Noto Sans (12pt) [GTK2/3/4]
Cursor: default (24px)
Terminal: kitty
CPU: Intel Xeon E3-1230 v3 (8) @ 3.7GHz
GPU: Nvidia GeForce GTX 1070
Memory: 2645MiB / 15947MiB (16%)
Disk (/): 96GB / 219GB (43%)
Locale: de_DE.UTF-8
```

[qtile-git_build_errors.txt](https://github.com/qtile/qtile/files/8149442/qtile-git_build_errors.txt)

**Comment by m-col** [comment]
In the meantime, you can probably get away with not running the check when building the package. In fact it has caused a couple problems, and they are probably incidental and also unimportant, so perhaps it's best to just remove the check from the pkgbuild altogether.

**Comment by thingsiplay** [comment]
Would I need to do this with every update? And I am not 100% sure what lines to comment out or delete. This is the first time I do the process of editing AUR build scripts.

**Comment by elParaguayo** [comment]
Hmm. That test is failing because `keyring` is installed locally. It passes on CI because we'd get an `ImportError` which we just ignore.

@m-col It might be best to disable that test in the aur files as there's no control over third party libraries whereas the widget specific tests tend to involve patching.

**Comment by m-col** [comment]
> @m-col It might be best to disable that test in the aur files as there's no control over third party libraries whereas the widget specific tests tend to involve patching.

Yeah, agreed. I don't think our test suite is reliable enough to be running on other people's machines... :laughing: :sob: 

@thingsiplay I just pushed a change to the pkgbuild that disables the tests, so if you fetch it again it should build without running the tests.

**Comment by elParaguayo** [comment]
Ideally, the tests should be run in a clean environment, not in the user's day-to-day environment.

**Comment by m-col** [comment]
True - just like AUR PKGBUILD's :wink:

**Comment by thingsiplay** [comment]
A few seconds before your last message, I figured it out and completed the build/install process successfully. But I thought the bug "Widget crashed: Systray (click to hide)" is solved on the Git (as @elParaguayo explained this in Reddit) and a different bug with the widget.sep we talked before. So I am not 100% if everything works fine for me. How can I test if the current installed version is the up to date from Git? BTW I have logout and login, just to make sure.

**Comment by elParaguayo** [comment]
It _should_ be solved. Please don't say we're still getting that error...

**Comment by thingsiplay** [comment]
Yeah, I didn't want talk about all issues in this thread, just wanted make sure how to know that I am running the current version from Git. Then my confused-head just had the idea to check the package with `pamac search qtile` and it is `qtile-git    [Installiert] 0.20.0.r69.g52ac53bf-1  AUR`, so there is no doubt about it.

I will then create a new issue or so about these topics.

**Comment by thingsiplay** [comment]
I am really sorry for the reopening and closing multiple times, because I am currently confused. The problem is, I am not even sure if the newest version from Git is in use currently, because none of the (told) fixes are in effect and the new MonadThreeCol does not work. It sounds like I still use an older version of Qtile? How can I ensure the current loaded up version is from Git? 
I ask here first, because I really think that my current build (just a few hours ago) or active Qtile is an old version? 

The moment I add `layout.MonadThreeCol()`, I get following message:
```
python3 ~/.config/qtile/config.py
Traceback (most recent call last):
  File "/home/tuncay/.config/qtile/config.py", line 597, in <module>
    layout.MonadThreeCol(
AttributeError: module 'libqtile.layout' has no attribute 'MonadThreeCol'
```

Here is some command outputs:
```
$ grep --color=auto "^class"  /usr/lib/python3.10/site-packages/libqtile/layout/xmonad.py 
class MonadTall(_SimpleLayoutBase):
class MonadWide(MonadTall):
class MonadThreeCol(MonadTall):

$ pamac search qtile-git
qtile-git      [Installiert] 0.20.0.r69.g52ac53bf-1  AUR

$ which -a qtile
/home/tuncay/.local/bin/qtile
/usr/bin/qtile

$ /home/tuncay/.local/bin/qtile --version
0.20.0
$ ls -alFh /home/tuncay/.local/bin/*qtile
-rwxr-xr-x 1 tuncay tuncay 219 28. Jan 10:58 /home/tuncay/.local/bin/qtile*

$ /usr/bin/qtile --version
0.20.0
$ ls -alFh /usr/bin/*qtile 
-rwxr-xr-x 1 root root 998 27. Feb 22:20 /usr/bin/qtile*
```

**Comment by elParaguayo** [comment]
I did wonder if you had a local version installed too. You must have cloned the repo and done `pip install .` at some point.

The one installed via pamac should be in `/use/bin` but you're probably running the local one.

Remove the local installation and you should be ok.

**Comment by thingsiplay** [comment]
That's it, exactly as you said! I removed it with pip3 and logout+login. Now i get "0.20.1.dev69+g52ac53bf" for `qtile --version`. And no bugs anymore and MonadThreeCol works. I'll close now, this time for real. Thank you guys for taking your time.
