### ISSUE TITLE
ModuleNotFoundError: No module named 'xcffib.ffi_build'

### ISSUE THREAD

**Issue by ebiscaia** [qtile/qtile#4290]
## Maintainers update

**If you get this error, rollback to xcffib 1.3.0 with something like `pip install --force-reinstall xcffib==1.3.0` and then install Qtile with `pip install --no-use-pep517 --no-build-isolation qtile`.**

We're currently breaking stuff so that it gets much simpler to install Qtile in a very near future.

Thank you for your understanding!

PS: You can read more about the context and track progress here: https://github.com/Kozea/cairocffi/issues/214

--- 

### The issue:

Hi guys,

After trying to update qtile (from Github) in my Fedora machine I bumped with this issue:
```
Defaulting to user installation because normal site-packages is not writeable
Processing /home/eddie/qtile
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      /usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py:264: UserWarning: Unknown distribution option: 'use_scm_version'
        warnings.warn(msg)
      Failed to find pulseaudio headers. PulseVolume widget will be unavailable
      Failed to find pywlroots. Wayland backend libinput configuration will be unavailable.
      Traceback (most recent call last):
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/usr/lib/python3.11/site-packages/setuptools/build_meta.py", line 484, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 105, in <module>
        File "/usr/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 476, in __init__
          _Distribution.__init__(
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 282, in __init__
          self.finalize_options()
        File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 900, in finalize_options
          ep(self)
        File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 920, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/home/eddie/.local/lib/python3.11/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
          add_cffi_module(dist, cffi_module)
        File "/home/eddie/.local/lib/python3.11/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
          execfile(build_file_name, mod_vars)
        File "/home/eddie/.local/lib/python3.11/site-packages/cffi/setuptools_ext.py", line 25, in execfile
          exec(code, glob, glob)
        File "libqtile/backend/x11/xcursors_ffi_build.py", line 25, in <module>
          from xcffib.ffi_build import ffi as xcffib_ffi
      ModuleNotFoundError: No module named 'xcffib.ffi_build'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I also tried some of the solution [here](https://github.com/qtile/qtile/issues/4265) to no avail.

Thanks,

Eddie

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Can you downgrade to xcffib 1.3.0 for now?

**Comment by ebiscaia** [comment]
Hi,

Now I managed to install qtile, but now I ended up being stuck in the tty.

`raise QtileError: no DISPLAY set`

Funny thing everything was working fine before the update

**Comment by elParaguayo** [comment]
How are you starting qtile. That suggests the X server isn't running.

**Comment by ebiscaia** [comment]
First, I tried with lightdm, which returns to the login screen. Then on the try with
`qtile start`

**Comment by elParaguayo** [comment]
It won't start from TTY unless you're using Wayland.

If it returns to login screen then that suggests qtile crashed. Anything in the log file?

**Comment by ebiscaia** [comment]
`TypeError: Initializer for ctype ‘xcb_connection_t *’ appears to be ‘xcb_connection_t *’ but the types are different (check that you are not e.g. mixing up different ffi instances)’`

**Comment by ramnes** [comment]
It seems that you're still using xcffib 1.4.0, did you downgrade to 1.3.0 ?

**Comment by ebiscaia** [comment]
Well I don't know what I was doing wrong because I was using this sequence:

```
pip install --no-cache xcffib==1.3.0
pip install --no-build-isolation --no-cache --upgrade --ignore-installed "cairocffi[xcb]"
python -m pip install  --no-build-isolation --no-cache --upgrade .
```
And that was leading to the errors above. Note that I also tried
`pip install --no-build-isolation --no-cache --upgrade --ignore-installed "cairocffi[xcb]==1.3.0"`
with no success.

My solution was:
```
pip install -I --force-reinstall --no-cache xcffib==1.3.0
```
and then install qtile.

Also is worth to note that after installing cairocffi[xcb] a folder of xcffib 1.4 version was created. It may be related with @tych0 issue

Thanks anyway guys.

**Comment by ramnes** [comment]
@tych0 cairocffi hasn't released the inline thing yet

**Comment by tych0** [comment]
> @tych0 cairocffi hasn't released the inline thing yet

Ah, right. this isn't the cairo cast. Gotta read closer.

**Comment by ramnes** [comment]
I just added a note on the OP and pinned the issue until we finish this "migration" since I guess most newcomers will hit this.

**Comment by cr1ogen** [comment]
Go back to version 1.3.0, it doesn't work for me. I get the same output: `ModuleNotFoundError: No module named 'xcffib.ffi_build'`

**Comment by ramnes** [comment]
Your Qtile still talks with 1.4.0 somehow. There really should be no other reason for that error to happen.

**Comment by ramnes** [comment]
Then read OP

**Comment by R0derick** [comment]
So how I solve this error?

**Comment by elParaguayo** [comment]
Did you downgrade `xcffib` to 1.3.0 as per the message at the top of this thread?

**Comment by R0derick** [comment]
Yes I downgrade xcffib to 1.3.0 but not work

**Comment by elParaguayo** [comment]
Is it the same error message? There's really no reason for that error message with 1.3.0 so I suspect you've still got it installed somehow.

**Comment by R0derick** [comment]
How remove packages with pip?

**Comment by R0derick** [comment]
![IMG_20230607_153222.jpg](https://github.com/qtile/qtile/assets/44153541/98c978bb-a289-46c3-9f90-d4b401f91955)

I get this error with xcffib 1.3.0

**Comment by elParaguayo** [comment]
`pip uninstall xcffib` to uninstall. Then try `pip install --no-cache-dir --ignore-installed xcffib==1.3.0`.

**Comment by R0derick** [comment]
I try this before, not work

**Comment by ramnes** [comment]
Can you come on IRC or Discord so that we can check that more directly?

**Comment by R0derick** [comment]
> Can you come on IRC or Discord so that we can check that more directly?

Yes

**Comment by ramnes** [comment]
@R0derick @cr1ogen Another user on Discord had the same problem and we got it working. Can you try to install Qtile with `pip install --no-use-pep517 --no-build-isolation qtile`?

**Comment by cr1ogen** [comment]
> @R0derick @cr1ogen Another user on Discord had the same problem and we got it working. Can you try to install Qtile with `pip install --no-use-pep517 --no-build-isolation qtile`?

No work for me,  but I try to install it outside of a virtual environment, I don't know if that will have something to do with it

**Comment by ramnes** [comment]
Alright then come to Discord / IRC if you want me to investigate

**Comment by cr1ogen** [comment]
> Alright then come to Discord / IRC if you want me to investigate

I was just looking at your chat with Alex on discord, but now I have to get back to work (i'm from Argentina xD). Thanks anyway

**Comment by amonetlol** [comment]
> > Alright then come to Discord / IRC if you want me to investigate
> 
> I was just looking at your chat with Alex on discord, but now I have to get back to work (i'm from Argentina xD). Thanks anyway

I'm Alex from discord, I'll describe the step by step I used to install qtile.

The following steps were used on Ubuntu 23.04:

Required packages: python3-virtualenv python3-pip

mkdir ~/qtile
python3 -m virtualenv ~/qtile
source ~/qtile/bin/activate

pip install xcffib==1.3.0
pip install --no-cache-dir cairocffi
pip install --no-use-pep517 --no-build-isolation qtile

OPTIONAL: pip install dbus-next

#Leaving the virtualenv
deactivate

When installing qtile by pip, it does not create the xsessions entry and also does not create the /usr/share/doc/qtile/default_config.py file

Alternative default config file:
https://github.com/qtile/qtile/blob/master/libqtile/resources/default_config.py

OPTIONAL:
install package: python3-virtualenv-clone

#move virtualenv folder 'qtile' for /opt/qtile
sudo virtualenv-clone ~/qtile /opt/qtile

#replace user
sudo chown -R user:user /opt/qtile

#set qtile for enviroment
mkdir ~/.local/share/bin
ln -s /opt/qtile/bin/qtile ~/.local/share/bin/qtile

#add PATH ~/.local/share/bin on .bashrc or .zshrc
export PATH="$HOME/.local/share/bin:$PATH"

#creating an entry in xsessions | /usr/share/xsessions/qtile.desktop
[Desktop Entry]
Name=Qtile
Comment=Qtile Session
Exec=/opt/qtile/bin/qtile start
Type=Application
X-GDM-SessionRegisters=true
Keywords=wm;tiling

**Comment by cr1ogen** [comment]
> > > Alright then come to Discord / IRC if you want me to investigate
> > 
> > 
> > I was just looking at your chat with Alex on discord, but now I have to get back to work (i'm from Argentina xD). Thanks anyway
> 
> I'm Alex from discord, I'll describe the step by step I used to install qtile.
> 
> The following steps were used on Ubuntu 23.04:
> 
> Required packages: python3-virtualenv python3-pip
> 
> mkdir ~/qtile python3 -m virtualenv ~/qtile source ~/qtile/bin/activate
> 
> pip install xcffib==1.3.0 pip install --no-cache-dir cairocffi pip install --no-use-pep517 --no-build-isolation qtile
> 
> OPTIONAL: pip install dbus-next
> 
> #Leaving the virtualenv deactivate
> 
> When installing qtile by pip, it does not create the xsessions entry and also does not create the /usr/share/doc/qtile/default_config.py file
> 
> Alternative default config file: https://github.com/qtile/qtile/blob/master/libqtile/resources/default_config.py
> 
> OPTIONAL: install package: python3-virtualenv-clone
> 
> #move virtualenv folder 'qtile' for /opt/qtile sudo virtualenv-clone ~/qtile /opt/qtile
> 
> #replace user sudo chown -R user:user /opt/qtile
> 
> #set qtile for enviroment mkdir ~/.local/share/bin ln -s /opt/qtile/bin/qtile ~/.local/share/bin/qtile
> 
> #add PATH ~/.local/share/bin on .bashrc or .zshrc export PATH="$HOME/.local/share/bin:$PATH"
> 
> #creating an entry in xsessions | /usr/share/xsessions/qtile.desktop [Desktop Entry] Name=Qtile Comment=Qtile Session Exec=/opt/qtile/bin/qtile start Type=Application X-GDM-SessionRegisters=true Keywords=wm;tiling

Thanks Alex for responding!! I followed the steps you did but when installing qtile it gives me another kind of error

```pip install --no-use-pep517 --no-build-isolation qtile
Collecting qtile
  Using cached qtile-0.22.1.tar.gz (488 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [75 lines of output]
      /home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/config/setupcfg.py:515: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      /home/cr1ogen/qtile/lib/python3.11/site-packages/wlroots/__pycache__/_cffi__x58fcf130x56f3363a.c:265:10: fatal error: wlr/version.h: No existe el fichero o el directorio
        265 | #include <wlr/version.h>
            |          ^~~~~~~~~~~~~~~
      compilation terminated.
      Traceback (most recent call last):
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 186, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 1007, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/cffi/ffiplatform.py", line 51, in _build
          dist.run_command('build_ext')
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
          self._build_extensions_serial()
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 549, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 599, in compile
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 188, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-uchgdyok/qtile_22a8f79921d74f9b82ccf0c39e8f522a/setup.py", line 105, in <module>
          cffi_modules=get_cffi_modules(),
                       ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-uchgdyok/qtile_22a8f79921d74f9b82ccf0c39e8f522a/setup.py", line 89, in get_cffi_modules
          import wlroots.ffi_build
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/wlroots/ffi_build.py", line 2930, in <module>
          check_version()
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/wlroots/ffi_build.py", line 52, in check_version
          wlroots_version = load_wlroots_version()
                            ^^^^^^^^^^^^^^^^^^^^^^
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/wlroots/ffi_build.py", line 39, in load_wlroots_version
          lib = ffi.verify("#include <wlr/version.h>")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/cffi/api.py", line 468, in verify
          lib = self.verifier.load_library()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/cffi/verifier.py", line 105, in load_library
          self._compile_module()
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/cffi/verifier.py", line 202, in _compile_module
          outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/cffi/ffiplatform.py", line 22, in compile
          outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/cffi/ffiplatform.py", line 58, in _build
          raise VerificationError('%s: %s' % (e.__class__.__name__, e))
      cffi.VerificationError: CompileError: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I'm still waiting for them to fix the problem. Thank you so much

**Comment by ramnes** [comment]
@cr1ogen This is another problem, can you please open another issue?

**Comment by cr1ogen** [comment]
> @cr1ogen This is another problem, can you please open another issue?

I did, sorry for the delay

**Comment by ramnes** [comment]
Should be fixed if you install Qtile from source: `pip install git+https://github.com/qtile/qtile@master`

And you don't have to install xcffib and cairocffi yourself anymore!

I'll try to push a beta release so that it gets even easier to install (i.e. `pip install --pre qtile`).

**Comment by bodograumann** [comment]
I am kinda lost. Nothing works anymore after the recent update.
Is the AUR package qtile-wayland-git still broken? It doesnt seem to work for me.
I tried installing with the above pip install git... command into a venv, but then I just get ModuleNotFoundError: No module named 'pywayland'

Is there a way to install an older working version of the AUR package?

**Comment by ramnes** [comment]
> I am kinda lost. Nothing works anymore after the recent update.
Is the AUR package qtile-wayland-git still broken? It doesnt seem to work for me.

> Is there a way to install an older working version of the AUR package?

Sorry if I'm being rude, but this repo is about Qtile, not Arch Linux

> I tried installing with the above pip install git... command into a venv, but then I just get ModuleNotFoundError: No module named 'pywayland'

If you want to run on Wayland, you most likely want to install Qtile with the extra-dependencies: `pip install qtile[wayland]`

Considering your error in particular, I guess you need to install pywayland, as indicated.

**Comment by bodograumann** [comment]
> Sorry if I'm being rude, but this repo is about Qtile, not Arch Linux

I thought because the AUR package is maintained by @m-col , it would be good to keep the discussion related to this issue in one place. Sorry if I misjudged this. More clarity on this would be appreciated. I will add a comment to the AUR package page. (Due to some unrelated breakage in xkeyboardconfig I wasn't able to log in there earlier)

I found out how to select a specific older revision of the git repo, so now I am using the qtile version from 3 weeks ago again.

> If you want to run on Wayland, you most likely want to install Qtile with the extra-dependencies: `pip install qtile[wayland]`

Ah, yeah that sounds right, I just couldn't remember the exact syntax. Thanks for reminding me.
Unforunately even after installing the missing dependencies with pip by trial and error, all I got was a segfault.
Seems like the same problem I had when trying to test the wlroots-0.16 branch. I tried asking there how to properly test qtile in a venv (so not using the system packages I guess?), but haven't gotten an answer.
If there is some documentation about this, I would be very grateful if you could point me to it.

Feel free to continue this discussion in https://github.com/qtile/qtile/pull/3985, seeing as it now departs more from the original issue.
