### ISSUE TITLE
Windows don't get resized when they exit full-screen

### ISSUE THREAD

**Issue by PhoenixClank** [qtile/qtile#4859]
### Issue description

1. Have a layout where windows can't span the entire screen (for example because of a bar, or other tiled windows)
2. Make a window full-screen
3. Exit full-screen
4. The window is moved to its correct tile but retains its full-screen size, potentially obscuring other windows or extending off-screen

Example screenshot, before making the image viewer full-screen:
![the file manager and image viewer occupy half the available space each](https://github.com/qtile/qtile/assets/30195074/7bfaf718-a5e8-409d-81a7-1ce35172f420)
After exiting full-screen:
![the image viewer extends off-screen, only half the image can be seen](https://github.com/qtile/qtile/assets/30195074/47b0e81c-235e-4d55-9a06-05658e2cc621)

The window does get properly resized after making it float and then tile again.

### Version

0.26.1.dev0+ge4b4bb8b.d20240523

### Backend

Wayland (experimental)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by jwijenbergh** [comment]
This is fixed in git, we will do a release soon

**Comment by PhoenixClank** [comment]
The release has happened, the version is now 0.26.1.dev0+ge4b4bb8b.d20240713, but this behavior still shows.

**Comment by PhoenixClank** [comment]
Now on version 0.27 and this is fixed thank you!
