### ISSUE TITLE
Screen reconfiguration mostly doesn't work

### ISSUE THREAD

**Issue by 3hhh** [qtile/qtile#5071]
### Issue description

Whenever I dock or undock my laptop, qtile usually fails to reconfigure the screen and I e.g. see the rectangle of the smaller screen on the large one or qtile fails to detect that one of my scripts just turned off the small monitor.

Restarting qtile helps. Sometimes normalizing the windows is also sufficient.

### Version

0.29

### Backend

X11 (default)

### Config

Reproducible with the default config.

### Logs

```text
2024-11-05 20:43:06,814 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 318, in clear
    self.clear_rect()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 234, in clear_rect
    with cairocffi.Context(self._xcb_surface) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/cairocffi/context.py", line 100, in __init__
    self._init_pointer(cairo.cairo_create(target._pointer))
                                          ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_pointer'
2024-11-05 20:43:07,312 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 318, in clear
    self.clear_rect()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 234, in clear_rect
    with cairocffi.Context(self._xcb_surface) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/cairocffi/context.py", line 100, in __init__
    self._init_pointer(cairo.cairo_create(target._pointer))
                                          ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_pointer'
2024-11-05 20:43:07,316 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 318, in clear
    self.clear_rect()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 234, in clear_rect
    with cairocffi.Context(self._xcb_surface) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/cairocffi/context.py", line 100, in __init__
    self._init_pointer(cairo.cairo_create(target._pointer))
                                          ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_pointer'
2024-11-05 20:43:07,319 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 318, in clear
    self.clear_rect()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 234, in clear_rect
    with cairocffi.Context(self._xcb_surface) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/cairocffi/context.py", line 100, in __init__
    self._init_pointer(cairo.cairo_create(target._pointer))
                                          ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_pointer'
2024-11-05 20:43:29,096 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 318, in clear
    self.clear_rect()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 234, in clear_rect
    with cairocffi.Context(self._xcb_surface) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/cairocffi/context.py", line 100, in __init__
    self._init_pointer(cairo.cairo_create(target._pointer))
                                          ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_pointer'
2024-11-05 20:43:29,105 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 318, in clear
    self.clear_rect()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 234, in clear_rect
    with cairocffi.Context(self._xcb_surface) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/cairocffi/context.py", line 100, in __init__
    self._init_pointer(cairo.cairo_create(target._pointer))
                                          ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_pointer'
2024-11-05 20:43:29,108 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 318, in clear
    self.clear_rect()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 234, in clear_rect
    with cairocffi.Context(self._xcb_surface) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/cairocffi/context.py", line 100, in __init__
    self._init_pointer(cairo.cairo_create(target._pointer))
                                          ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_pointer'
2024-11-05 20:43:30,320 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 318, in clear
    self.clear_rect()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 234, in clear_rect
    with cairocffi.Context(self._xcb_surface) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/cairocffi/context.py", line 100, in __init__
    self._init_pointer(cairo.cairo_create(target._pointer))
                                          ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_pointer'
2024-11-05 20:44:51,189 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 318, in clear
    self.clear_rect()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 234, in clear_rect
    with cairocffi.Context(self._xcb_surface) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/cairocffi/context.py", line 100, in __init__
    self._init_pointer(cairo.cairo_create(target._pointer))
                                          ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_pointer'
2024-11-05 20:44:51,218 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 318, in clear
    self.clear_rect()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 234, in clear_rect
    with cairocffi.Context(self._xcb_surface) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/cairocffi/context.py", line 100, in __init__
    self._init_pointer(cairo.cairo_create(target._pointer))
                                          ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_pointer'
2024-11-05 20:44:53,892 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 318, in clear
    self.clear_rect()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 234, in clear_rect
    with cairocffi.Context(self._xcb_surface) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/cairocffi/context.py", line 100, in __init__
    self._init_pointer(cairo.cairo_create(target._pointer))
                                          ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_pointer'
2024-11-05 20:45:40,678 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 318, in clear
    self.clear_rect()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 234, in clear_rect
    with cairocffi.Context(self._xcb_surface) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/cairocffi/context.py", line 100, in __init__
    self._init_pointer(cairo.cairo_create(target._pointer))
                                          ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_pointer'
2024-11-05 20:45:41,250 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 315, in clear
    self.ctx.save()
    ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'save'
2024-11-05 20:45:41,265 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 315, in clear
    self.ctx.save()
    ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'save'
2024-11-05 20:46:10,239 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 315, in clear
    self.ctx.save()
    ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'save'
2024-11-05 20:46:10,432 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 315, in clear
    self.ctx.save()
    ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'save'
2024-11-05 20:46:10,443 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 315, in clear
    self.ctx.save()
    ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'save'
2024-11-05 20:46:12,062 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 315, in clear
    self.ctx.save()
    ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'save'
2024-11-05 20:49:35,773 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 315, in clear
    self.ctx.save()
    ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'save'
2024-11-05 20:49:35,808 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/user/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 315, in clear
    self.ctx.save()
    ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'save'
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by tych0** [comment]
I fixed the first error in your logs in #5059. Funny that somehow I didn't see your second stack trace while fixing the first one. but anyway, can you try the above branch and confirm that it fixes things?

**Comment by tych0** [comment]
Derp, I meant #5074 :)

**Comment by 3hhh** [comment]
Hi, thanks for the quick fix attempt!

Unfortunately it only fixes it in 50% of the cases (sometimes it works, sometimes it doesn't). Looks like a race condition to me.

Current stack trace:
```
AttributeError: 'NoneType' object has no attribute '_pointer'
2024-11-07 17:23:03,812 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/tripleh/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/tripleh/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/tripleh/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/tripleh/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/tripleh/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/tripleh/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 320, in clear
    self.clear_rect()
  File "/home/tripleh/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 234, in clear_rect
    with cairocffi.Context(self._xcb_surface) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tripleh/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/cairocffi/context.py", line 100, in __init__
    self._init_pointer(cairo.cairo_create(target._pointer))
                                          ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_pointer'
```

I once again reproduced it with the default config. Alternatively, my current config is now also available [here](https://github.com/3hhh/qubes-qtile).

**Comment by tych0** [comment]
Did you just cherry pick the above onto a tag? You'll need to have current git master, which has f642d3aa80f5dbe6a2838ad470ea24506a3fc20a that is a fix for the crash you posted.

**Comment by tych0** [comment]
But anyway, I will merge the other fix too, then with git master *both* of these should be fixed.

**Comment by 3hhh** [comment]
I'm sorry, but I still get the stack trace even with the commit you mentioned (Yes, I cherry-picked with 0.29 as base; now I also included the commit you mentioned).

So I fear we'll have to re-open this one.

Or is there any other commit in master that is related?
At least [I don't see any at the moment](https://github.com/qtile/qtile/compare/v0.29.0...master)...

Most recent trace with both patches applied:
```
2024-11-08 17:00:56,761 ERROR libqtile hook.py:fire():L196 Error in hook screen_change
Traceback (most recent call last):
  File "/home/tripleh/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/hook.py", line 194, in fire
    i(*args, **kwargs)
  File "/home/tripleh/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 444, in reconfigure_screens
    self._process_screens()
  File "/home/tripleh/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/home/tripleh/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/config.py", line 479, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/tripleh/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/bar.py", line 331, in _configure
    self.drawer.clear(self.background)
  File "/home/tripleh/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/base/drawer.py", line 320, in clear
    self.clear_rect()
  File "/home/tripleh/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 234, in clear_rect
    with cairocffi.Context(self._xcb_surface) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tripleh/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/cairocffi/context.py", line 100, in __init__
    self._init_pointer(cairo.cairo_create(target._pointer))
                                          ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_pointer'
```

**Comment by tych0** [comment]
Oh, I see. Probably I fixed the wayland version of this bug, but I didn't realize the x11 backend had totally custom overrides for workarounds:

https://github.com/qtile/qtile/blob/792ceba439aa93f6f64441db7ccfc382a0a19f81/libqtile/backend/x11/drawer.py#L232-L233

can you try https://github.com/qtile/qtile/commit/02d0bd42d49efd5e970ca0ca3e96db764024cbd5 and see if that really fixes it?

**Comment by 3hhh** [comment]
Hm, the trace is gone, yes.

However the screen reconfiguration sometimes still doesn't work and sometimes it works.

Also, I now ran into this one once:
```
2024-11-08 18:44:02,096 ERROR libqtile core.py:_xpoll():L359 Got an exception in poll loop
Traceback (most recent call last):
  File "/home/tripleh/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/x11/core.py", line 334, in _xpoll
    self.handle_event(event)
  File "/home/tripleh/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/backend/x11/core.py", line 301, in handle_event
    ret = target(event)
          ^^^^^^^^^^^^^
  File "/home/tripleh/qubes-qtile/trunk/qtile-env/lib64/python3.11/site-packages/libqtile/widget/systray.py", line 220, in handle_ClientMessage
    parent = self.bar.window.window
             ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'window'
```

**Comment by tych0** [comment]
Heh, this makes me think there's some more holistic solution we need to all of this. Like completely masking off all x11 events until we are re-bootstrapped.

**Comment by tych0** [comment]
I'll have a look and see if I can come up with something, although I'm a little afraid we'll uncover edge cases like the ScreenChangeNotify branch has :(

**Comment by 3hhh** [comment]
Well, it just took me 6 docks and undocks to reproduce the aforementioned trace, i.e. https://github.com/qtile/qtile/pull/5075 already helped in many cases.

I believe that usually the undock operation is causing issues, which (wild guess) may be because qtile has no screen to draw to for a few seconds as it takes that much for my script to realize the undock and then re-enable the laptop screen via `xrandr`. So probably it's reproducible by plugging in and out a screen cable for a while; possibly one would also have to switch between two different screens...
