### ISSUE TITLE
AttributeError: 'libqtile.core.manager.Qtile' has no attribute current_window

### ISSUE THREAD

**Issue by sashah86** [qtile/qtile#5135]
### Issue description

# Firstly, thank you for your work and contributions.

I have been using Qtile for a few years and am very happy with it. From time to time, I have encountered some issues, but I was usually able to fix them myself.

Recently, I encountered a minor issue:

In my logs, I saw the following error:
 ## AttributeError: <class 'libqtile.core.manager.Qtile'> has no attribute current_window 

_In my humble opinion, the fix for this issue is to add a try/except block or hasattr check._

**Location of the Issue:**
libqtile/backend/x11/core.py

**Current Code:**
```
771     def handle_DestroyNotify(self, event) -> None:  # noqa: N802
772         assert self.qtile is not None
773
774         self.qtile.unmanage(event.window)
775         self.update_client_lists()
776         if self.qtile.current_window is None:
777             self.conn.fixup_focus()
```
**Proposed code:**
```
771     def handle_DestroyNotify(self, event) -> None:  # noqa: N802
772         assert self.qtile is not None
773
774         self.qtile.unmanage(event.window)
775         self.update_client_lists()
776         try:
777             if self.qtile.current_window is None:
778                 self.conn.fixup_focus()
779         except AttributeError:
780             self.conn.fixup_focus()
```

**Alternative proposed code:**
```
771     def handle_DestroyNotify(self, event) -> None:  # noqa: N802
772         assert self.qtile is not None
773
774         self.qtile.unmanage(event.window)
775         self.update_client_lists()
776         if not hasattr(self.qtile, 'current_window') or self.qtile.current_window is None:
777             self.conn.fixup_focus()
```

### Version

0.29.1.dev57+g6dedf4dc

### Backend

X11 (default)

### Logs

```text
16 2024-12-24 00:18:37,278 ERROR libqtile core.py:_xpoll():L362 Got an exception in poll loop
  17 Traceback (most recent call last):
  18   File "/usr/lib/python3.13/site-packages/libqtile/backend/x11/core.py", line 337, in _xpoll
  19     self.handle_event(event)
  20     ~~~~~~~~~~~~~~~~~^^^^^^^
  21   File "/usr/lib/python3.13/site-packages/libqtile/backend/x11/core.py", line 304, in handle_event
  22     ret = target(event)
  23   File "/usr/lib/python3.13/site-packages/libqtile/backend/x11/core.py", line 776, in handle_DestroyNotify
  24     if self.qtile.current_window is None:
  25        ^^^^^^^^^^^^^^^^^^^^^^^^^
  26   File "/usr/lib/python3.13/site-packages/libqtile/command/base.py", line 283, in __getattr__
  27     raise AttributeError(f"{self.__class__} has no attribute {name}")
  28 AttributeError: <class 'libqtile.core.manager.Qtile'> has no attribute current_window
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by tych0** [comment]
Hi, thanks for the report. The "real" fix for this is #5020, though I still have not had time to debug the test failure there completely, it should be safe to use. I would appreciate any additional testing on that branch.

**Comment by nazar-pc** [comment]
This bugs me as well. 0.28.0 works and 0.29.0/0.30.0 do not despite not mentioning any breaking changes in the changelog.

**Comment by slacksystem** [comment]
I'm still getting this error all over my logs, is a fix in the works?

**Comment by nazar-pc** [comment]
I'm on 0.32.0 and I no longer see it, so I guess it may have been fixed. Have you tried the latest version?

**Comment by slacksystem** [comment]
> I'm on 0.32.0 and I no longer see it, so I guess it may have been fixed. Have you tried the latest version?

I'm also running 0.32.0 and I'm still getting the error in the OP but I am also getting 
```
2025-07-03 14:01:18,142 ERROR libqtile start.py:start():L111 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/libqtile/scripts/start.py", line 109, in start
    q.loop()
    ~~~~~~^^
  File "/usr/lib/python3.13/site-packages/libqtile/core/manager.py", line 205, in loop
    asyncio.run(self.async_loop())
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/asyncio/base_events.py", line 719, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/libqtile/core/manager.py", line 217, in async_loop
    self.load_config(initial=True)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/libqtile/core/manager.py", line 171, in load_config
    self.core.on_config_load(initial)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/libqtile/backend/x11/core.py", line 269, in on_config_load
    win = window.Window(item, self.qtile)
  File "/usr/lib/python3.13/site-packages/libqtile/backend/x11/window.py", line 1697, in __init__
    self.set_group()
    ~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/libqtile/backend/x11/window.py", line 1995, in set_group
    if group != self.qtile.current_screen.group:
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/libqtile/command/base.py", line 283, in __getattr__
    raise AttributeError(f"{self.__class__} has no attribute {name}")
AttributeError: <class 'libqtile.core.manager.Qtile'> has no attribute current_screen. Did you mean: 'current_group'?
```
Dunno if that is related but I thought I'd include it here for completeness.

**Comment by nazar-pc** [comment]
Then it'd be helpful for maintainers to see your config, which original author didn't provide either
