### ISSUE TITLE
Different screen order in v0.32

### ISSUE THREAD

**Issue by adolfocorreia** [qtile/qtile#5305]
After updating qtile from v0.31 to v0.32, the order of my two screens changed.  The index numbers associated with each monitor (0 and 1) are now reversed.

The culprit seems to be commit #50b8cf9, in which xrandr is priorized over xinerama.  Note that, in the old version of the `query_crtcs` method, the loop was over CRTC objects and now it loops over Output objects.

At least on my system, such objects are ordered differently as shown be the following script results:

Script:
```
from libqtile.backend.x11 import xcbq
import xcffib
conn = xcbq.Connection(":0")
wid = conn.screens[0].root.wid
ext = conn.conn(xcffib.randr.key)

print("CRTCs:")
for crtc in ext.GetScreenResources(wid).reply().crtcs:
    crtc_info = ext.GetCrtcInfo(crtc, xcffib.CurrentTime).reply()
    print(f"{crtc_info.x} {crtc_info.y} {crtc_info.width} {crtc_info.height}")

print("Outputs:")
for output in ext.GetScreenResources(wid).reply().outputs:
    output_info = ext.GetOutputInfo(output, xcffib.CurrentTime).reply()
    if not output_info.crtc:
        continue
    crtc_info = ext.GetCrtcInfo(output_info.crtc, xcffib.CurrentTime).reply()
    print(f"{crtc_info.x} {crtc_info.y} {crtc_info.width} {crtc_info.height}")
```

Result:
```
CRTCs:
0 0 2560 1440
2560 0 2560 1440
0 0 0 0

Outputs:
2560 0 2560 1440
0 0 2560 1440
```

Note also that xrandr orders my monitors the same way as that of the CRTCs objects:

```
> xrandr --listmonitors
Monitors: 2
 0: +*HDMI-2 2560/597x1440/336+0+0  HDMI-2
 1: +DP-1 2560/597x1440/336+2560+0  DP-1
```

I don't know what the expected behaviour is supposed to be here, but I suspect the `query_crtcs` method should respect the monitors order as listed by the `xrandr` command.

**Comment by tych0** [comment]
Hmm, I would have expected them to be in the same order. Can you print the crtc name as well in your first output?

But in general, X11 doesn't guarantee stable ordering across reboots of these devices, so the real fix for this is #5274, any testing on that would be much appreciated.

**Comment by tych0** [comment]
Also,
>  Note that, in the old version of the query_crtcs method, the loop was over CRTC objects and now it loops over Output objects.

In the old code, `query_crtcs()` was never actually called, because we depended on xinerama, so I don't think it matters what it did. My guess is that xrandr is doing some sorting of the crtcs, but I have not actually looked at the code.

**Comment by adolfocorreia** [comment]
Thank you for your reply!

> Hmm, I would have expected them to be in the same order. Can you print the crtc name as well in your first output?

I don't know about CRTC names, but I got their IDs. I also got the outputs names:

```
print("CRTCs:")
for crtc in ext.GetScreenResources(wid).reply().crtcs:
    crtc_info = ext.GetCrtcInfo(crtc, xcffib.CurrentTime).reply()
    print(f"{crtc}: {crtc_info.x} {crtc_info.y} {crtc_info.width} {crtc_info.height}")
print("Outputs:")
for output in ext.GetScreenResources(wid).reply().outputs:
    output_info = ext.GetOutputInfo(output, xcffib.CurrentTime).reply()
    if not output_info.crtc:
        continue
    crtc_info = ext.GetCrtcInfo(output_info.crtc, xcffib.CurrentTime).reply()
    print(f"{output_info.name.to_string()} - {output_info.crtc}: {crtc_info.x} {crtc_info.y} {crtc_info.width} {crtc_info.height}")
```
```
CRTCs:
63: 0 0 2560 1440
62: 2560 0 2560 1440
64: 0 0 0 0

Outputs:
DP-1 - 62: 2560 0 2560 1440
HDMI-2 - 63: 0 0 2560 1440
```

The `outputs` order (62, 63) is really different from the `crtcs` order (63, 62). The `outputs` order is also different from `xrandr --listmonitors`.

> But in general, X11 doesn't guarantee stable ordering across reboots of these devices, so the real fix for this is [#5274](https://github.com/qtile/qtile/pull/5274), any testing on that would be much appreciated.

I'll take a look at it.

> In the old code, query_crtcs() was never actually called, because we depended on xinerama, so I don't think it matters what it did. My guess is that xrandr is doing some sorting of the crtcs, but I have not actually looked at the code.

Good point, the old version was indeed getting the screen information from xinerama and not from randr/crtcs. But, at least in this particular case, the order would be correct if it read from randr/crtcs. Not sure if it generalizes, though.

**Comment by tych0** [comment]
You can print the output names with:
```
--- script.py.orig	2025-06-29 09:19:35.321480518 -0600
+++ script.py	2025-06-29 09:19:23.271458669 -0600
@@ -10,9 +10,10 @@
     print(f"{crtc_info.x} {crtc_info.y} {crtc_info.width} {crtc_info.height}")

 print("Outputs:")
 for output in ext.GetScreenResources(wid).reply().outputs:
     output_info = ext.GetOutputInfo(output, xcffib.CurrentTime).reply()
+    print(f"{output_info.name.to_string()}: ")
     if not output_info.crtc:
         continue
     crtc_info = ext.GetCrtcInfo(output_info.crtc, xcffib.CurrentTime).reply()
     print(f"{crtc_info.x} {crtc_info.y} {crtc_info.width} {crtc_info.height}")
```

Looking [here](https://gitlab.freedesktop.org/xorg/app/xrandr/-/blob/12ed42b3fa0e59bc41ca4eeb40d9a5675f3f82e2/xrandr.c#L1783) and [here](https://gitlab.freedesktop.org/xorg/app/xrandr/-/blob/12ed42b3fa0e59bc41ca4eeb40d9a5675f3f82e2/xrandr.c#L755-765) it seems like xrandr just does them in order? But maybe it sorts primary to be first? We could do that. (If you throw in a `GetOutputInfo()` to your script, or just grep xrandr for primary, we should be able to figure this part out.)

**Comment by adolfocorreia** [comment]
The order of outputs in my system is a little odd, but `xrandr` lists the primary monitor (HDMI-2) first when listing monitors:

```
> xrandr --current | grep "^[^ ]"
Screen 0: minimum 320 x 200, current 5120 x 1440, maximum 16384 x 16384
DP-1 connected 2560x1440+2560+0 (normal left inverted right x axis y axis) 597mm x 336mm
HDMI-1 disconnected (normal left inverted right x axis y axis)
HDMI-2 connected primary 2560x1440+0+0 (normal left inverted right x axis y axis) 597mm x 336mm
DP-2 disconnected (normal left inverted right x axis y axis)

> xrandr --listmonitors
Monitors: 2
 0: +*HDMI-2 2560/597x1440/336+0+0  HDMI-2
 1: +DP-1 2560/597x1440/336+2560+0  DP-1
```

**Comment by adolfocorreia** [comment]
Here is the output of the python script printing all Output names before the `continue` statement:

```
CRTCs:
63: 0 0 2560 1440
62: 2560 0 2560 1440
64: 0 0 0 0

Outputs:
DP-1:
DP-1 - 62: 2560 0 2560 1440
HDMI-1:
HDMI-2:
HDMI-2 - 63: 0 0 2560 1440
DP-2:
```

The CRTCs order (63,62) is the same as `xrandr --listmonitors` and the Outputs order (62,63) is the same as `xrandr --current`.

**Comment by tych0** [comment]
Ok, so I guess I'm confused as to what the behavior should be, given that you can get them to output in both orders :). I guess the real question is: if xrandr and xinerama didn't list displays in the same order, what should we do?

I was thinking:
1. use xrandr (or autorandr, or whatever) to set up geometries of monitors how you want
2. have qtile bind Screen() objects via serial number, so that these things are stably ordered (in particular, my docking station often reverses the order of monitors without warning, so I have been running the serial number patchset for a long time because of that)

But if there is some way to also guarantee that we list monitors in the same way that xinerama always did (e.g. by always using crtc ordering), perhaps that's good, but in my experience, even that is not stable.

**Comment by adolfocorreia** [comment]
In my opinion, the best option would definitely be 2, but I don`t know how complex it would be to push the patch to master.

Regarding 1, I wonder if there is any way a user can force the reordering of the Outputs with `xrandr`. For instance, I set my system with the command below, setting HDMI-2 "to the front", but `xrandr --current` still lists it after DP-1. On the other hand, `xrandr --listmonitors` seems to respect the user instructions. If that is really the case, then the best alternative would be for qtile to assume the CRTCs order when using `xrandr`, which is the same as `xinerama`'s, at least on my system.

```
xrandr --dpi 96 --output HDMI-2 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output DP-1 --mode 2560x1440 --pos 2560x0 --rotate normal
```

A third alternative would be to create a new configuration option in qtile, allowing the user to choose between xrandr and xinerama orderings.

**Comment by tych0** [comment]
The best thing about (2) is that I've written the code in #5274 :)

> A third alternative would be to create a new configuration option in qtile, allowing the user to choose between xrandr and xinerama orderings.

Yep, if you boot your X11 server with randr disabled, it should fall back to xinerama. But I think we do want to move forward with supporting randr in a better form, so I think it's best to figure out the correct solution vs. trying to emulate xinerama.

**Comment by lowerclasswarfare** [comment]
Okay I'm gonna hop in and call second on this issue. I just started using qtile very recently, and it's been pretty good so far. I'm running on Gentoo, and the current stable version is 0.31. Qtile and literally ALL the other window managers I have played with over time have respected my monitor setup, and updating to 0.32 definitely breaks the monitor order. So something definitely got messed up. I normally run i3, and occasionally XFCE for floating stuff if I want. I don't have any issues with my randr startup scripts, it's just that the order isn't being respected since the update to 0.32.

**Comment by tych0** [comment]
Yeah, I will try and figure out some solution to this. Apologies - I have been out of town for the last ~10 days.

**Comment by felixmde** [comment]
I've found this issue after encountering the same error. I use `autorandr` for my screen configuration and after an update the screens were no longer ordered as before (I have different information on my primary and secondary monitors).

The quick (and probably very dirty) workaround for me was to do `screens.reverse()` in my `config.py` after the screens have been defined. That fixes the issue for me for setups with one and two external monitors.

Edit: Nevermind. The reverse did not actually work. I had manually adjusted the order and that's what actually worked. So, that's obviously not a good workaround because it will only work for one configuration...

**Comment by tych0** [comment]
Can you confirm your expected order is the order of the crtcs as in the script from the initial report? I'm wondering if it's as simple as iterating over crtcs and finding outputs vs. the reverse.

**Comment by tych0** [comment]
Or maybe a different way: does `xrandr -q` show things in the order people expect? Can someone annotate an `xrandr -q` with the way their physical layout was, and the way their xinerama layout was?

For me they were both in the same order, and as near as I can tell they are in Output (not Crtc) order in xrandr: https://gitlab.freedesktop.org/xorg/app/xrandr/-/blob/12ed42b3fa0e59bc41ca4eeb40d9a5675f3f82e2/xrandr.c#L3703-3710

I want to fix this, but... I'm really not sure what's wrong here.

**Comment by zordsdavini** [comment]
For me the solution would be to set primary monitor first. `xrandr -q` for me gives random order but parameter `primary` is for right monitor:
```
Screen 0: minimum 320 x 200, current 3200 x 1080, maximum 16384 x 16384
eDP-1 connected 1280x720+1920+360 (normal left inverted right x axis y axis) 309mm x 174mm
   1920x1080     60.00 +  59.97    59.96    59.93    48.00
   1680x1050     59.95    59.88
<...>
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 480mm x 270mm
   1920x1080     74.97*+  60.00    50.00    59.94
   1680x1050     59.88
<...>
DP-2 disconnected (normal left inverted right x axis y axis)
```
For me HDMI-1 should be firsts.

**Comment by tych0** [comment]
Ok, thank you for confirming. Does https://github.com/qtile/qtile/commit/01c426a667e58a208d3c5fb59e495d6aedfdcdf2 fix it for you?

**Comment by zordsdavini** [comment]
@tych0 for me fix with primary works super

**Comment by tych0** [comment]
Ok, 0.33.0 has this patch, so hopefully this is fixed for everyone else too? I'll wait a bit to close this to see if we get any other complaints...

**Comment by misumisumi** [comment]
This problem still persists.
Now, I connected three monitors.
In my case, `xrandr --listmonitors` and `xrandr --query` are displayed in reverse order.
In other words, if the order (correct) of `xrandr --listmonitor` is 1, 2, 3, then `xrandr --query` is 3, 2, 1, and qtile is initialized in the order 1, 3, 2.


It might be this problem caused by the NVIDIA GPU.
According to the [Appendix B](https://download.nvidia.com/XFree86/Linux-x86_64/304.137/README/xconfigoptions.html) in the NVIDIA Linux driver documentation, the NVIDIA driver provides Xinerama extension support.
(also [explanation of multi display](https://download.nvidia.com/XFree86/Linux-x86_64/535.261.03/README/configtwinview.html))
The order of displays is controlled by `nvidiaXineramaInfo`.
Indeed, prioritizing xinerama, as in v0.31.0, resolved the issue.
The nvidia-driver appears to have a unique (as many say) movement.
In summary, I think it would be better to revert xinerama to the code that prioritizes

**Comment by felixmde** [comment]
I can confirm that the fix worked for my setup. Thanks!

I don't know if this is helpful at this point, but here is the xrandr output for my setup.

```
[~]$ xrandr --query 
Screen 0: minimum 320 x 200, current 4480 x 1440, maximum 16384 x 16384
eDP connected 1920x1080+0+0 (normal left inverted right x axis y axis) 309mm x 174mm
   1920x1080     60.02*+  48.00  
(...)
DisplayPort-3 connected primary 2560x1440+1920+0 (normal left inverted right x axis y axis) 527mm x 296mm
   2560x1440     59.95*+  74.78  
(...)
```
