### ISSUE TITLE
Keybindings are not active after closing emacs

### ISSUE THREAD

**Issue by tollerm** [qtile/qtile#755]
Hi,
I have some strange problem with a dynamic group where emacs is spawned. In my setup I have a few normal groups which are always active and two dynamic groups for emacs and firefox, respectively. When I start emacs from an empty static group, after its closing qtile stops to react on pressed keys. It seems that screen does not get a focus when the 'emacs' dynamic group becomes non-active. Qtile resumes to react on pressed keys again when a group in the groupbox is selected with a mouse.  After starting emacs from a terminal or from a non-empty group, keybindings remain active after exiting emacs. With firefox everything works as advertised, i.e.  keybindings operate without any problem after closing firefox.  
Best regards,
Toller

**Comment by alexf91** [comment]
I actually have the same problem with an application called CQRLOG. I'm not using dynamic groups.
Qtile starts reacting to key presses after clicking the bar, but not the screen.

**Comment by flacjacket** [comment]
Unfortunately I don't have dynamic groups to know about this. I can try it out later, tho.

**Comment by tollerm** [comment]
I've updated Emacs to version 25 and now after closing Emacs I can use all keys in normal way. Really strange, but my problem is solved.

**Comment by alexf91** [comment]
I wrote a little script to reproduce the bug and get the debug output (xautomation package required)

```python
from libqtile.command import Client
from subprocess import Popen, PIPE
import time
import sys
import os

group_sequence = '''keydown Super_L
key 2
keyup Super_L
'''

def keypress(sequence):
    p = Popen(['xte'], stdin=PIPE)
    p.communicate(input=sequence.encode('ascii'))

with open(os.path.expanduser('~/.qtile.log')) as fd:
    offset = len(fd.readlines())

c = Client()
c.debug()
c.group['3'].toscreen()
c.spawn(sys.argv[1])
time.sleep(1)
c.window.kill()
time.sleep(1)
keypress(group_sequence)
c.warning()

with open(os.path.expanduser('~/.qtile.log')) as fd:
    lines = [x.strip() for x in fd.readlines()[offset:]]

for line in lines:
    print(line)
```

Here's the output:
```
2015-10-10 15:25:27,950 DEBUG cmd_debug:1182 Switching to DEBUG threshold
2015-10-10 15:25:27,950 INFO eof_received:186 Sending result on receive EOF
2015-10-10 15:25:27,951 INFO eof_received:188 Closing connection on receive EOF
2015-10-10 15:25:27,952 INFO connection_made:162 Connection made to server
2015-10-10 15:25:27,953 INFO data_received:166 Data recieved by server
2015-10-10 15:25:27,954 INFO eof_received:170 EOF recieved by server
2015-10-10 15:25:27,955 INFO call:92 Command: toscreen((), {})
2015-10-10 15:25:27,957 INFO fire:270 Internal event: setgroup((), {})
2015-10-10 15:25:27,959 INFO fire:270 Internal event: focus_change((), {})
2015-10-10 15:25:27,960 INFO fire:270 Internal event: layout_change((<libqtile.layout.xmonad.MonadTall object at 0x7f6e285a32e8>, <libqtile.group._Group object at 0x7f6e285a3358>), {})
2015-10-10 15:25:27,961 INFO eof_received:186 Sending result on receive EOF
2015-10-10 15:25:27,961 INFO eof_received:188 Closing connection on receive EOF
2015-10-10 15:25:28,028 DEBUG _xpoll:732 UnmapNotify
2015-10-10 15:25:28,029 INFO _xpoll:734 Handling: UnmapNotify
2015-10-10 15:25:28,030 DEBUG _xpoll:732 EnterNotify
2015-10-10 15:25:28,030 INFO _xpoll:734 Handling: EnterNotify
2015-10-10 15:25:28,031 DEBUG _xpoll:732 UnmapNotify
2015-10-10 15:25:28,032 INFO _xpoll:734 Handling: UnmapNotify
2015-10-10 15:25:28,032 DEBUG _xpoll:732 ConfigureNotify
2015-10-10 15:25:28,033 INFO _xpoll:734 Handling: ConfigureNotify
2015-10-10 15:25:28,035 INFO connection_made:162 Connection made to server
2015-10-10 15:25:28,036 INFO data_received:166 Data recieved by server
2015-10-10 15:25:28,036 INFO eof_received:170 EOF recieved by server
2015-10-10 15:25:28,037 INFO call:92 Command: spawn(('emacs',), {})
2015-10-10 15:25:28,045 INFO eof_received:186 Sending result on receive EOF
2015-10-10 15:25:28,046 INFO eof_received:188 Closing connection on receive EOF
2015-10-10 15:25:28,374 DEBUG _xpoll:732 ConfigureRequest
2015-10-10 15:25:28,374 INFO _xpoll:734 Handling: ConfigureRequest
2015-10-10 15:25:28,375 DEBUG _xpoll:732 ConfigureRequest
2015-10-10 15:25:28,375 INFO _xpoll:734 Handling: ConfigureRequest
2015-10-10 15:25:28,375 DEBUG _xpoll:732 ConfigureRequest
2015-10-10 15:25:28,375 INFO _xpoll:734 Handling: ConfigureRequest
2015-10-10 15:25:28,376 DEBUG _xpoll:732 ClientMessage
2015-10-10 15:25:28,376 INFO _xpoll:734 Handling: ClientMessage
2015-10-10 15:25:28,376 DEBUG _xpoll:732 ConfigureRequest
2015-10-10 15:25:28,376 INFO _xpoll:734 Handling: ConfigureRequest
2015-10-10 15:25:28,377 DEBUG _xpoll:732 MapRequest
2015-10-10 15:25:28,377 INFO _xpoll:734 Handling: MapRequest
2015-10-10 15:25:28,378 INFO fire:270 Internal event: window_name_change((), {})
2015-10-10 15:25:28,385 INFO fire:270 Internal event: net_wm_icon_change((Window('emacs@ideapad'),), {})
2015-10-10 15:25:28,386 INFO fire:270 Internal event: client_new((Window('emacs@ideapad'),), {})
2015-10-10 15:25:28,387 INFO fire:270 Internal event: setgroup((), {})
2015-10-10 15:25:28,388 INFO fire:270 Internal event: group_window_add((), {})
2015-10-10 15:25:28,389 INFO fire:270 Internal event: client_focus((Window('emacs@ideapad'),), {})
2015-10-10 15:25:28,389 INFO fire:270 Internal event: focus_change((), {})
2015-10-10 15:25:28,390 INFO fire:270 Internal event: client_focus((Window('emacs@ideapad'),), {})
2015-10-10 15:25:28,391 INFO fire:270 Internal event: client_managed((Window('emacs@ideapad'),), {})
2015-10-10 15:25:28,392 DEBUG _xpoll:732 ConfigureRequest
2015-10-10 15:25:28,392 INFO _xpoll:734 Handling: ConfigureRequest
2015-10-10 15:25:28,393 DEBUG _xpoll:732 MapRequest
2015-10-10 15:25:28,394 INFO _xpoll:734 Handling: MapRequest
2015-10-10 15:25:28,395 DEBUG _xpoll:732 ClientMessage
2015-10-10 15:25:28,396 INFO _xpoll:734 Handling: ClientMessage
2015-10-10 15:25:28,396 DEBUG _xpoll:732 ConfigureNotify
2015-10-10 15:25:28,396 INFO _xpoll:734 Handling: ConfigureNotify
2015-10-10 15:25:28,396 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,397 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,397 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: WM_STATE
2015-10-10 15:25:28,397 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,397 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,397 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: _NET_WM_DESKTOP
2015-10-10 15:25:28,398 DEBUG _xpoll:732 ConfigureNotify
2015-10-10 15:25:28,398 INFO _xpoll:734 Handling: ConfigureNotify
2015-10-10 15:25:28,398 DEBUG _xpoll:732 ConfigureNotify
2015-10-10 15:25:28,398 INFO _xpoll:734 Handling: ConfigureNotify
2015-10-10 15:25:28,398 DEBUG _xpoll:732 ConfigureNotify
2015-10-10 15:25:28,398 INFO _xpoll:734 Handling: ConfigureNotify
2015-10-10 15:25:28,399 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,399 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,399 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: WM_STATE
2015-10-10 15:25:28,399 DEBUG _xpoll:732 ConfigureNotify
2015-10-10 15:25:28,400 INFO _xpoll:734 Handling: ConfigureNotify
2015-10-10 15:25:28,400 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,400 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,400 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: WM_STATE
2015-10-10 15:25:28,400 DEBUG _xpoll:732 ConfigureNotify
2015-10-10 15:25:28,401 INFO _xpoll:734 Handling: ConfigureNotify
2015-10-10 15:25:28,401 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,401 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,401 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: _NET_WM_STATE
2015-10-10 15:25:28,401 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,402 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,402 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: _NET_WM_OPAQUE_REGION
2015-10-10 15:25:28,402 INFO handle_PropertyNotify:1176 Unknown window property: _NET_WM_OPAQUE_REGION
2015-10-10 15:25:28,402 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,402 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,402 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: _NET_WM_OPAQUE_REGION
2015-10-10 15:25:28,403 INFO handle_PropertyNotify:1176 Unknown window property: _NET_WM_OPAQUE_REGION
2015-10-10 15:25:28,417 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,417 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,417 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: XdndAware
2015-10-10 15:25:28,417 INFO handle_PropertyNotify:1176 Unknown window property: XdndAware
2015-10-10 15:25:28,418 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,418 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,418 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: _MOTIF_DRAG_RECEIVER_INFO
2015-10-10 15:25:28,418 INFO handle_PropertyNotify:1176 Unknown window property: _MOTIF_DRAG_RECEIVER_INFO
2015-10-10 15:25:28,418 DEBUG _xpoll:732 ConfigureNotify
2015-10-10 15:25:28,419 INFO _xpoll:734 Handling: ConfigureNotify
2015-10-10 15:25:28,419 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,419 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,419 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: WM_NORMAL_HINTS
2015-10-10 15:25:28,421 INFO fire:270 Internal event: client_focus((Window('emacs@ideapad'),), {})
2015-10-10 15:25:28,421 DEBUG _xpoll:732 ConfigureRequest
2015-10-10 15:25:28,421 INFO _xpoll:734 Handling: ConfigureRequest
2015-10-10 15:25:28,422 DEBUG _xpoll:732 ConfigureNotify
2015-10-10 15:25:28,422 INFO _xpoll:734 Handling: ConfigureNotify
2015-10-10 15:25:28,422 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,422 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,422 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: WM_STATE
2015-10-10 15:25:28,422 DEBUG _xpoll:732 ConfigureNotify
2015-10-10 15:25:28,423 INFO _xpoll:734 Handling: ConfigureNotify
2015-10-10 15:25:28,423 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,424 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,424 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: _NET_WM_OPAQUE_REGION
2015-10-10 15:25:28,424 INFO handle_PropertyNotify:1176 Unknown window property: _NET_WM_OPAQUE_REGION
2015-10-10 15:25:28,462 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,462 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,462 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: WM_NORMAL_HINTS
2015-10-10 15:25:28,463 INFO fire:270 Internal event: client_focus((Window('emacs@ideapad'),), {})
2015-10-10 15:25:28,464 DEBUG _xpoll:732 ConfigureRequest
2015-10-10 15:25:28,464 INFO _xpoll:734 Handling: ConfigureRequest
2015-10-10 15:25:28,464 DEBUG _xpoll:732 ConfigureNotify
2015-10-10 15:25:28,465 INFO _xpoll:734 Handling: ConfigureNotify
2015-10-10 15:25:28,465 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,465 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,465 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: WM_STATE
2015-10-10 15:25:28,465 DEBUG _xpoll:732 ConfigureNotify
2015-10-10 15:25:28,466 INFO _xpoll:734 Handling: ConfigureNotify
2015-10-10 15:25:28,466 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,466 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,466 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: _NET_WM_OPAQUE_REGION
2015-10-10 15:25:28,466 INFO handle_PropertyNotify:1176 Unknown window property: _NET_WM_OPAQUE_REGION
2015-10-10 15:25:28,504 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,504 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,505 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: WM_NORMAL_HINTS
2015-10-10 15:25:28,507 INFO fire:270 Internal event: client_focus((Window('emacs@ideapad'),), {})
2015-10-10 15:25:28,507 DEBUG _xpoll:732 ConfigureRequest
2015-10-10 15:25:28,507 INFO _xpoll:734 Handling: ConfigureRequest
2015-10-10 15:25:28,508 DEBUG _xpoll:732 ConfigureNotify
2015-10-10 15:25:28,508 INFO _xpoll:734 Handling: ConfigureNotify
2015-10-10 15:25:28,508 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,508 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,508 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: WM_STATE
2015-10-10 15:25:28,509 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,509 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,509 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: _NET_WM_OPAQUE_REGION
2015-10-10 15:25:28,509 INFO handle_PropertyNotify:1176 Unknown window property: _NET_WM_OPAQUE_REGION
2015-10-10 15:25:28,509 DEBUG _xpoll:732 ConfigureRequest
2015-10-10 15:25:28,509 INFO _xpoll:734 Handling: ConfigureRequest
2015-10-10 15:25:28,510 DEBUG _xpoll:732 ConfigureNotify
2015-10-10 15:25:28,511 INFO _xpoll:734 Handling: ConfigureNotify
2015-10-10 15:25:28,511 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,511 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,511 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: _NET_WM_OPAQUE_REGION
2015-10-10 15:25:28,512 INFO handle_PropertyNotify:1176 Unknown window property: _NET_WM_OPAQUE_REGION
2015-10-10 15:25:28,512 DEBUG _xpoll:732 ConfigureNotify
2015-10-10 15:25:28,512 INFO _xpoll:734 Handling: ConfigureNotify
2015-10-10 15:25:28,513 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,513 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,513 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: WM_NORMAL_HINTS
2015-10-10 15:25:28,515 INFO fire:270 Internal event: client_focus((Window('emacs@ideapad'),), {})
2015-10-10 15:25:28,516 DEBUG _xpoll:732 ConfigureRequest
2015-10-10 15:25:28,516 INFO _xpoll:734 Handling: ConfigureRequest
2015-10-10 15:25:28,516 DEBUG _xpoll:732 ConfigureNotify
2015-10-10 15:25:28,516 INFO _xpoll:734 Handling: ConfigureNotify
2015-10-10 15:25:28,517 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,517 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,517 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: WM_STATE
2015-10-10 15:25:28,517 DEBUG _xpoll:732 ConfigureNotify
2015-10-10 15:25:28,517 INFO _xpoll:734 Handling: ConfigureNotify
2015-10-10 15:25:28,518 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:28,518 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:28,518 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: _NET_WM_OPAQUE_REGION
2015-10-10 15:25:28,518 INFO handle_PropertyNotify:1176 Unknown window property: _NET_WM_OPAQUE_REGION
2015-10-10 15:25:29,050 INFO connection_made:162 Connection made to server
2015-10-10 15:25:29,051 INFO data_received:166 Data recieved by server
2015-10-10 15:25:29,052 INFO eof_received:170 EOF recieved by server
2015-10-10 15:25:29,052 INFO call:92 Command: kill((), {})
2015-10-10 15:25:29,054 INFO eof_received:186 Sending result on receive EOF
2015-10-10 15:25:29,054 INFO eof_received:188 Closing connection on receive EOF
2015-10-10 15:25:29,236 DEBUG _xpoll:732 PropertyNotify
2015-10-10 15:25:29,237 INFO _xpoll:734 Handling: PropertyNotify
2015-10-10 15:25:29,238 DEBUG handle_PropertyNotify:1136 PropertyNotifyEvent: _NET_WM_USER_TIME
2015-10-10 15:25:29,243 DEBUG _xpoll:732 DestroyNotify
2015-10-10 15:25:29,244 INFO _xpoll:734 Handling: DestroyNotify
2015-10-10 15:25:29,244 DEBUG _xpoll:732 DestroyNotify
2015-10-10 15:25:29,245 INFO _xpoll:734 Handling: DestroyNotify
2015-10-10 15:25:29,245 DEBUG _xpoll:732 EnterNotify
2015-10-10 15:25:29,246 INFO _xpoll:734 Handling: EnterNotify
2015-10-10 15:25:29,246 INFO fire:270 Internal event: client_mouse_enter((Window('emacs@ideapad'),), {})
2015-10-10 15:25:29,247 INFO _xpoll:734 Handling: EnterNotify
2015-10-10 15:25:29,247 DEBUG _xpoll:732 UnmapNotify
2015-10-10 15:25:29,248 INFO _xpoll:734 Handling: UnmapNotify
2015-10-10 15:25:29,248 INFO fire:270 Internal event: client_killed((Window('emacs@ideapad'),), {})
2015-10-10 15:25:29,249 INFO _del:249 Add dgroup timer
2015-10-10 15:25:29,251 DEBUG _xpoll:732 UnmapNotify
2015-10-10 15:25:29,251 INFO _xpoll:734 Handling: UnmapNotify
2015-10-10 15:25:29,251 DEBUG _xpoll:732 EnterNotify
2015-10-10 15:25:29,252 INFO _xpoll:734 Handling: EnterNotify
2015-10-10 15:25:29,252 DEBUG _xpoll:732 DestroyNotify
2015-10-10 15:25:29,253 INFO _xpoll:734 Handling: DestroyNotify
2015-10-10 15:25:29,253 DEBUG _xpoll:732 DestroyNotify
2015-10-10 15:25:29,253 INFO _xpoll:734 Handling: DestroyNotify
2015-10-10 15:25:29,254 DEBUG _xpoll:732 DestroyNotify
2015-10-10 15:25:29,254 INFO _xpoll:734 Handling: DestroyNotify
2015-10-10 15:25:29,255 DEBUG _xpoll:732 DestroyNotify
2015-10-10 15:25:29,255 INFO _xpoll:734 Handling: DestroyNotify
2015-10-10 15:25:29,283 DEBUG _xpoll:732 ConfigureNotify
2015-10-10 15:25:29,283 INFO _xpoll:734 Handling: ConfigureNotify
2015-10-10 15:25:30,066 DEBUG _xpoll:732 MappingNotify
2015-10-10 15:25:30,067 INFO _xpoll:734 Handling: MappingNotify
2015-10-10 15:25:30,077 DEBUG _xpoll:732 MappingNotify
2015-10-10 15:25:30,077 INFO _xpoll:734 Handling: MappingNotify
2015-10-10 15:25:30,082 INFO connection_made:162 Connection made to server
2015-10-10 15:25:30,083 INFO data_received:166 Data recieved by server
2015-10-10 15:25:30,083 INFO eof_received:170 EOF recieved by server
2015-10-10 15:25:30,084 INFO call:92 Command: warning((), {})
2015-10-10 15:25:30,085 WARNING cmd_warning:1192 Switching to WARNING threshold
```

**Comment by ramnes** [comment]
The bug is still present with Emacs 26, apparently (see #1188).

**Comment by trev-dev** [comment]
Just my 2 cents, but it almost feels like qtile "loses focus" when emacs exits. Key binds stop working until I click on another application in the same/some other workspace. This is a particularily troubling bug when Emacs is the _only app_ open when it closes, in which case I'm having to switch to a different tty session and restart the machine.

**Comment by ep12** [comment]
Is there a function being called when starting qtile that somehow binds the configured keys (and X handles those?) If that is the case and after emacs closes X deletes everything it knows then it would be possible to call that function after emacs quits and everything would be probably fine. I don't have any idea how X and keybindings work, but this is so annoying!

**Comment by whatacold** [comment]
> Just my 2 cents, but it almost feels like qtile "loses focus" when emacs exits.

Hmm, that's a good guess, I'm troubleshooting this problem and find out that if it happens Qtile's `handle_KeyPress` isn't called, so it makes sense if Qtile loses "focus".

> Key binds stop working until I click on another application in the same/some other workspace. This is a particularily troubling bug when Emacs is the _only app_ open when it closes, in which case I'm having to switch to a different tty session and restart the machine.

You can just click a group label on the bar, then Qtile is back to live again.

**Comment by whatacold** [comment]
At first, I think it may be a problem of GDM, but it turns out that it also happens with lightdm after testing with lightdm. So I think this should be a problem of Qtile.

**Comment by whatacold** [comment]
I've just confirmed that the problem is caused by sending the event of `WM_TAKE_FOCUS` in `focus()` in `window.py`, the issue is gone if I commented out the line of `send_event`, but figuring out how to fix it still need some time.

**Comment by whatacold** [comment]
Finally, I found out that it's because the timestamp for `WM_TAKE_FOCUS` is 0, thanks to `xtrace`, which has such a log that draws my attention(note that almost all bytes of the `data` field is 0x00):

    004:<:06eb: 44: Request(25): SendEvent propagate=false(0x00) destination=0x0020013f event-mask=0 ClientMessage(33) format=0x20 window=0x0020013f type=0xf2("WM_PROTOCOLS") data=0xf3,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00;

And along the way, I found an i3 [bugfix](https://github.com/i3/i3/commit/05f058581780de3b9c25d37ea4319122592dbec2) that may be relevant, it says "If input focus is set by the window manager, it is not necessary to send WM_TAKE_FOCUS because it has already taken focus." I'm not sure if it's necessary, so I just leave it as is.
